version: "3.8"

services:
  db:
    image: postgres:15.2
    volumes:
      - db:/var/lib/postgresql/data
      - ./database/Sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_database
    ports:
      - 5432:5432
    networks:
      - todo_app_network

  nginx:
    image: nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
    ports:
      - 3000:3000
    depends_on:
      - frontend
    networks:
      - todo_app_network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 80:80
    networks:
      - todo_app_network
    environment:
      - BACKEND_ORIGIN_CLIENT=${BACKEND_ORIGIN_CLIENT}

  todo_api:
    build:
      context: ./backend/TodoApi
    volumes:
      - ./backend/TodoApi:/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/todo_database
    ports:
      - 5001:5001
    networks:
      - todo_app_network
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db:

networks:
  todo_app_network:
    driver: bridge
